# Practical Exam: House sales

**RealAgents** is a real estate company that focuses on selling houses.  
RealAgents sells a variety of types of houses in one metropolitan area.  
Some houses sell slowly and sometimes require lowering the price in order to find a buyer.  
In order to stay competitive, RealAgents would like to optimize the listing prices of the houses it is trying to sell.  
They want to do this by predicting the sale price of a house given its characteristics.  
If they can predict the sale price in advance, they can decrease the time to sale.

---

### Data
The dataset contains records of previous houses sold in the area.

| Column Name      | Criteria                                                                                                                                  |
|------------------|------------------------------------------------------------------------------------------------------------------------------------------|
| **house_id**      | Nominal. Unique identifier for houses. Missing values not possible.                                                                        |
| **city**          | Nominal. The city in which the house is located. One of 'Silvertown', 'Riverford', 'Teasdale' and 'Poppleton'. Replace missing values with "Unknown". |
| **sale_price**    | Discrete. The sale price of the house in whole dollars. Values can be any positive number greater than or equal to zero. Remove missing entries. |
| **sale_date**     | Discrete. The date of the last sale of the house. Replace missing values with 2023-01-01.                                                  |
| **months_listed** | Continuous. The number of months the house was listed on the market prior to its last sale, rounded to one decimal place. Replace missing values with mean number of months listed, to one decimal place. |
| **bedrooms**      | Discrete. The number of bedrooms in the house. Any positive values greater than or equal to zero. Replace missing values with the mean number of bedrooms, rounded to the nearest integer. |
| **house_type**    | Ordinal. One of "Terraced" (two shared walls), "Semi-detached" (one shared wall), or "Detached" (no shared walls). Replace missing values with the most common house type. |
| **area**          | Continuous. The area of the house in square meters, rounded to one decimal place. Replace missing values with the mean, to one decimal place. |

### Task 1  
The team at RealAgents knows that the city that a property is located in makes a difference to the sale price.  
Unfortunately, they believe that this isn't always recorded in the data.

**Instructions:**
- Calculate the number of missing values in the 'city' column.
- You should use the data in the file "house_sales.csv".
- Your output should be an object named `missing_city`, which contains the number of missing values in this column.

In [1]:
# Part 1
import pandas as pd

# Load the data from the CSV file
house_sales = pd.read_csv("house_sales.csv")

# Print all unique values in the 'city' column
unique_cities = house_sales['city'].unique()

# Count the missing values represented by '--' in the 'city' column
missing_city = (house_sales['city'] == '--').sum()

# Output the result
print(missing_city)

73

### Task 2  
Before you fit any models, you will need to make sure the data is clean.

The table below shows what the data should look like. Create a cleaned version of the dataframe.

**Instructions:**
- You should start with the data in the file "house_sales.csv".
- Your output should be a dataframe named `clean_data`.
- All column names and values should match the criteria described below:

| **Column Name**  | **Criteria** |
| ---------------- | ------------ |
| **house_id**      | Nominal. Unique identifier for houses. Missing values not possible. |
| **city**          | Nominal. The city in which the house is located. One of 'Silvertown', 'Riverford', 'Teasdale' and 'Poppleton'. Replace missing values with "Unknown". |
| **sale_price**    | Discrete. The sale price of the house in whole dollars. Values can be any positive number greater than or equal to zero. Remove missing entries. |
| **sale_date**     | Discrete. The date of the last sale of the house. Replace missing values with 2023-01-01. |
| **months_listed** | Continuous. The number of months the house was listed on the market prior to its last sale, rounded to one decimal place. Replace missing values with the mean number of months listed, to one decimal place. |
| **bedrooms**      | Discrete. The number of bedrooms in the house. Any positive values greater than or equal to zero. Replace missing values with the mean number of bedrooms, rounded to the nearest integer. |
| **house_type**    | Ordinal. One of "Terraced", "Semi-detached", or "Detached". Replace missing values with the most common house type. |
| **area**          | Continuous. The area of the house in square meters, rounded to one decimal place. Replace missing values with the mean, to one decimal place. |

In [2]:
# Use this cell to write your code for Task 2
clean_data = house_sales.copy()

# 1. Replace missing values in 'city' with "Unknown"
clean_data['city'].replace('--', 'Unknown', inplace=True)

# 2. Remove rows with missing 'sale_price'
clean_data[clean_data['sale_price'].notna()]

# 3. Replace missing values in 'sale_date' with '2023-01-01'
clean_data['sale_date'].fillna('2023-01-01', inplace=True)

# 4. Replace missing values in 'months_listed' with the mean, rounded to 1 decimal place
mean_months_listed = round(clean_data['months_listed'].mean(), 1)
clean_data['months_listed'].fillna(mean_months_listed, inplace=True)

# 5. Replace missing values in 'bedrooms' with the mean, rounded to the nearest integer
mean_bedrooms = round(clean_data['bedrooms'].mean())
clean_data['bedrooms'].fillna(mean_bedrooms, inplace=True)

# 6. Replace missing values in 'house_type' with the most common house type
most_common_house_type = clean_data['house_type'].mode()[0]
clean_data['house_type'] = clean_data['house_type'].replace({
    'Det.': 'Detached',
    'Semi': 'Semi-detached',
    'Terr.': 'Terraced'
})
clean_data['house_type'].fillna(most_common_house_type, inplace=True)

# 7. Replace missing values in 'area' with the mean, rounded to 1 decimal place
clean_data['area'] = clean_data['area'].str.replace(' sq.m.', '', regex=False).astype(float)
clean_data['area'].dtype
mean_area = round(clean_data['area'].mean(), 1)
clean_data['area'].fillna(mean_area, inplace=True)

# Display the cleaned DataFrame
print(clean_data.head())

   house_id        city  sale_price   sale_date  months_listed  bedrooms  \
0   1217792  Silvertown       55943  2021-09-12            5.4         2
1   1900913  Silvertown      384677  2021-01-17            6.3         5
2   1174927   Riverford      281707  2021-11-10            6.9         6
3   1773666  Silvertown      373251  2020-04-13            6.1         6
4   1258487  Silvertown      328885  2020-09-24            8.7         5

      house_type   area
0  Semi-detached  107.8
1       Detached  498.8
2       Detached  542.5
3       Detached  528.4
4       Detached  477.1

/var/folders/t9/9j3z7g1s2vn9fgx4dcd5wsw80000gn/T/ipykernel_11537/3430976837.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  clean_data['city'].replace('--', 'Unknown', inplace=True)
/var/folders/t9/9j3z7g1s2vn9fgx4dcd5wsw80000gn/T/ipykernel_11537/3430976837.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  clean_data['sale_date'].fillna('2023-01-01', inplace=True)
/var/folders/t9/9j3z7g1s2vn9fgx4dcd5wsw80000gn/T/ipykernel_11537/3430976837.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  clean_data['months_listed'].fillna(mean_months_listed, inplace=True)
/var/folders/t9/9j3z7g1s2vn9fgx4dcd5wsw80000gn/T/ipykernel_11537/3430976837.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  clean_data['bedrooms'].fillna(mean_bedrooms, inplace=True)
/var/folders/t9/9j3z7g1s2vn9fgx4dcd5wsw80000gn/T/ipykernel_11537/3430976837.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  clean_data['house_type'].fillna(most_common_house_type, inplace=True)
/var/folders/t9/9j3z7g1s2vn9fgx4dcd5wsw80000gn/T/ipykernel_11537/3430976837.py:34: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  clean_data['area'].fillna(mean_area, inplace=True)

### Task 3

The team at RealAgents believes that the number of bedrooms is the biggest driver of house price.

Your task is to produce a table showing the average sale price and variance in sale price by the number of bedrooms.

**Instructions:**
- Start with the data in the file 'house_sales.csv'.
- Your output should be a dataframe named `price_by_rooms`.
- The dataframe should include the following three columns:
  - `bedrooms`: The number of bedrooms.
  - `avg_price`: The average sale price for houses with that number of bedrooms.
  - `var_price`: The variance in sale price for houses with that number of bedrooms.
- Round your answers to **1 decimal place**.

In [3]:
# Part 3

# Remove any rows where sale_price or bedrooms are missing
house_sales = house_sales.dropna(subset=['sale_price', 'bedrooms'])

# Group by 'bedrooms' and calculate average sale price and variance
price_by_rooms = house_sales.groupby('bedrooms').agg(
    avg_price=('sale_price', 'mean'),
    var_price=('sale_price', 'var')
).reset_index()

# Round the results to 1 decimal place
price_by_rooms['avg_price'] = price_by_rooms['avg_price'].round(1)
price_by_rooms['var_price'] = price_by_rooms['var_price'].round(1)

# Display the result
price_by_rooms.head()

   bedrooms  avg_price     var_price
0         2    67076.4  5.652896e+08
1         3   154665.1  2.378289e+09
2         4   234704.6  1.725211e+09
3         5   301515.9  2.484328e+09
4         6   375741.3  3.924432e+09

### Task 4

Your task is to fit a **baseline model** to predict the sale price of a house.

**Steps:**
1. **Train the model** using the data in **`train.csv`**.
2. **Predict the sale price** of houses using the **`validation.csv`** data.
3. Return a dataframe named **`base_result`** which should contain the following columns:
   - `house_id`: The unique identifier for each house.
   - `price`: The predicted sale price.

### Requirements:
- The `price` column should contain the predicted values based on the model you fitted.

In [4]:
# Task 4
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# Load the training and validation datasets
train_data = pd.read_csv("train.csv")
validation_data = pd.read_csv("validation.csv")

# Preprocess the training data
# Drop rows with missing sale_price
train_data = train_data.dropna(subset=['sale_price'])

# Handle categorical variables by using one-hot encoding for house_type and city
train_data = pd.get_dummies(train_data, columns=['house_type', 'city'], drop_first=True)

# Define features and target variable for the training set
X_train = train_data.drop(columns=['house_id', 'sale_price', 'sale_date'])
y_train = train_data['sale_price']

# Fit a linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Preprocess the validation data
# Handle categorical variables similarly as done in training
validation_data = pd.get_dummies(validation_data, columns=['house_type', 'city'], drop_first=True)

# Ensure the validation set has the same features as the training set
X_validation = validation_data.drop(columns=['house_id', 'sale_date'])
X_validation = X_validation.reindex(columns=X_train.columns, fill_value=0)

# Predict sale prices for the validation set
predicted_prices = model.predict(X_validation)

# Prepare the result DataFrame
base_result = pd.DataFrame({
    'house_id': validation_data['house_id'],
    'price': predicted_prices
})

# Round the predicted prices to whole dollars
base_result['price'] = base_result['price'].round(0).astype(int)

# Display the base result
base_result.head()

   house_id   price
0   1331375  121528
1   1630115  304387
2   1645745  384760
3   1336775  123976
4   1888274  271186

### Task 5

In this task, your objective is to fit a **comparison model** to predict the sale price of a house.

**Steps:**
1. **Train the comparison model** using the data in **`train.csv`**.
2. **Predict the sale price** of houses using the data from **`validation.csv`**.
3. Return a dataframe named **`compare_result`** which should contain the following columns:
   - `house_id`: The unique identifier for each house.
   - `price`: The predicted sale price from the comparison model.

### Requirements:
- The `price` column should include the predicted values from your newly fitted model for comparison purposes.

In [5]:
# Task 5
from sklearn.ensemble import RandomForestRegressor

# Load the training and validation datasets
train_data = pd.read_csv("train.csv")
validation_data = pd.read_csv("validation.csv")

# Preprocess the training data
# Drop rows with missing sale_price
train_data = train_data.dropna(subset=['sale_price'])

# Handle categorical variables by using one-hot encoding for house_type and city
train_data = pd.get_dummies(train_data, columns=['house_type', 'city'], drop_first=True)

# Define features and target variable for the training set
X_train = train_data.drop(columns=['house_id', 'sale_price', 'sale_date'])
y_train = train_data['sale_price']

# Fit a Random Forest Regressor model
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Preprocess the validation data
# Handle categorical variables similarly as done in training
validation_data = pd.get_dummies(validation_data, columns=['house_type', 'city'], drop_first=True)

# Ensure the validation set has the same features as the training set
X_validation = validation_data.drop(columns=['house_id', 'sale_date'])
X_validation = X_validation.reindex(columns=X_train.columns, fill_value=0)

# Predict sale prices for the validation set
predicted_prices = model.predict(X_validation)

# Prepare the result DataFrame
compare_result = pd.DataFrame({
    'house_id': validation_data['house_id'],
    'price': predicted_prices
})

# Round the predicted prices to whole dollars
compare_result['price'] = compare_result['price'].round(0).astype(int)

# Display the compare result
compare_result.head()

   house_id   price
0   1331375   81996
1   1630115  302920
2   1645745  404928
3   1336775  106559
4   1888274  267625